### ISSUE TITLE
Add .readthedocs.yaml

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-nyt#118]
Currently, our docs aren't building because we haven't configured anything. By default, Read the Docs uses old legacy tools when nothing is configured -- and that doesn't work.

Example: https://readthedocs.org/projects/django-nyt/builds/20372734/

**Comment by oscarmcm** [comment]
This might be enough?

```yaml
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
   configuration: docs/conf.py
python:
   install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```
