### ISSUE TITLE
Improve RTD build process

### ISSUE THREAD

**Issue by oscarmcm** [django-wiki/django-nyt#120]
_Originally posted by @benjaoming in https://github.com/django-wiki/django-nyt/issues/119#issuecomment-1534192339_

It does pass the build, but I believe this is not what we want in the end, this comes from the build log:

```txt
Processing /home/docs/checkouts/readthedocs.org/user_builds/django-nyt/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
WARNING: django-nyt 1.3 does not provide the extra 'docs'
Collecting django<4.3,>=2.2 (from django-nyt==1.3)
  Downloading Django-4.2.1-py3-none-any.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 186.8 MB/s eta 0:00:00
Collecting asgiref<4,>=3.6.0 (from django<4.3,>=2.2->django-nyt==1.3)
  Downloading asgiref-3.6.0-py3-none-any.whl (23 kB)
Collecting sqlparse>=0.3.1 (from django<4.3,>=2.2->django-nyt==1.3)
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 189.4 MB/s eta 0:00:00
Building wheels for collected packages: django-nyt
  Building wheel for django-nyt (pyproject.toml): started
  Building wheel for django-nyt (pyproject.toml): finished with status 'done'
  Created wheel for django-nyt: filename=django_nyt-1.3-py3-none-any.whl size=37182 sha256=aba75df76ec565f0d6a839f5765b41c06b3d4471f5bd5c95718397e11a33050b
  Stored in directory: /tmp/pip-ephem-wheel-cache-sy3lphk2/wheels/d6/35/b9/a2fd0913eb69cebf9dde1d242c2cb14ddfcc8153b48459626d
Successfully built django-nyt
Installing collected packages: sqlparse, asgiref, django, django-nyt
Successfully installed asgiref-3.6.0 django-4.2.1 django-nyt-1.3 sqlparse-0.4.4
```

As we don't have a `docs` mode in our `pyproject.toml` configuration (`pip install django-nyt[docs]`, sorry here)

So then, what I believe is the right process, it to add more install steps with the dependencies [listed here](https://github.com/django-wiki/django-nyt/blob/main/pyproject.toml#L130-L132)

Something like this I believe will do the trick:

```yaml
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
   configuration: docs/conf.py
python:
   install:
    - method: pip
      path: .
    - method: pip
      path: sphinx
    - method: pip
      path: channels
    - method: pip
      path: sphinx_rtd_theme
```

**Comment by oscarmcm** [comment]
Ohhhh I see!!

This:

```yaml
    - method: pip
      path: sphinx
```

will be transformed to `python sphinx/setup.py install`...

Does RDT support install packages without the need to use a requirement file?

**Comment by oscarmcm** [comment]
Ahhhh seems that [this is valid](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-commands)

```yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install pelican
    - pelican --settings docs/pelicanconf.py --output _readthedocs/html/ docs/
```

So maybe we can place many commands with `pip install` per each package.
